name: Code Coverage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - 0.*
      - 1.*

jobs:
  coverage:
    uses: mrgoodbytes8667/workflows/.github/workflows/code-coverage.yml@php8.1-8.2
    with:
      phpUnitVersion: 9.5
      coverageType: pcov