name: Tests By Symfony Version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main
      - 0.*
      - 1.*
  schedule:
    # Weekly on Mondays at 3pm UTC
    - cron:  '0 15 * * 1'

jobs:
  symfony53:
    uses: mrgoodbytes8667/workflows/.github/workflows/run-tests-by-version.yml@php8.1-8.2
    with:
      phpUnitVersion: 9.5
      symfony: 5.3

  symfony54:
    uses: mrgoodbytes8667/workflows/.github/workflows/run-tests-by-version.yml@php8.1-8.2
    with:
      phpUnitVersion: 9.5
      symfony: 5.4

  symfony60:
    uses: mrgoodbytes8667/workflows/.github/workflows/run-tests-by-version.yml@php8.1-8.2
    with:
      phpUnitVersion: 9.5
      symfony: 6.0

  symfony61:
    uses: mrgoodbytes8667/workflows/.github/workflows/run-tests-by-version.yml@php8.1-8.2
    with:
      phpUnitVersion: 9.5
      symfony: 6.1

  symfony62:
    uses: mrgoodbytes8667/workflows/.github/workflows/run-tests-by-version.yml@php8.1-8.2
    with:
      phpUnitVersion: 9.5
      symfony: 6.2